title: "Geometry and Vision with Deep Learning"
lang: en
description: Peking University
url: https://yixin26.github.io/blog/
theme: null

debug:
  compress: false
  dist: false
  extension: false

readme_index:
  with_frontmatter: true

sass:
  style: compress

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock

comments:

  gitalk: true
  gitalk_clientID: '9b578af8b23301f608fd'
  gitalk_Secret: 'db6c8649e36281a55ba221a7f99b20711ec6b68c'
  gitalk_repo: 'yixin26.github.io/blog'
  gitalk_owner: 'geometry'
  gitalk_admin: 'geometry'
  distractionFreeMode: true